### ISSUE TITLE
TODO challenge storing groceries

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#1015]
List of things that need to be added to the challenge storing groceries for RGO2020
- [ ] testing: spawn objects in gazebo
- [ ] Inspect shelves
    - [x] move up and down for different shelves
- [ ] Manipulate machine
    - [x] Move one item
    - [ ] Place next to similar item -designator
        - [x] Place next to other item
        - [x] Find similar item
        - [ ] Derive area from original object
    - [ ] Place objects high. similar to Grasp object high from #1010 

Extra
- [ ] Open door
    - [ ] create scafolding
