### ISSUE TITLE
TODO Challenge Receptionist

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#1018]
- [x] Person detection does not work all the time...
- [x] Fallback for failing person detection?
- [x] Fix launch files so that ED does not crash due to missing services (mentioned by Rein)
- [x] Challenge crashes (ED detect people not available)
- [ ] Rise robot before human-robot interaction
- [x] Check multiple volumes for emptiness
- [ ] Point at correct volume that is empty
- [x] For each seat, define various seat volumes
- [x] Check for Person entities in volumes, not for how full the volume is
