### ISSUE TITLE
Biestheuvel Merge TODO's

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#1139]
- [ ] tue-robocup #1133 
  - [x] Robot skills
      - [x] topological action planner 
      - [x] hero + amigo + sergio
      - [x] perception
  - [ ] robot smach states
      - [ ] open door
      - [x] move obstacle
      - [x] topological navigation 
- [x] topological_action_planner (including dependencies) tue-robotics/topological_action_planner#1
- [x] ed_python
  - [x] ed_python ed_python tue-robotics/ed_python#1
  ~~- [ ] ed_python (merge into biestheuvel branch)~~ --> Leave for now, fix this later
- [ ]  pykdl_ros
  - [x] pykydl_ros tue-robotics/pykdl_ros#1
  - [ ]  pykydl_ros (merge 'blindly' into biestheuvel branch, let CI run and merge into master) #1138

**Comment by PetervDooren** [comment]
Made this issue to keep track of what still needs to be done on the Biestheuvel PR. Feel free to edit and add parts

**Comment by MatthijsBurgh** [comment]
`ed_python` needs to be extended, a lot! We need to think about the module structure. As we have plugins in CPP, we might want to have a similar structure in python. We should be able to handle situations that not all cpp plugins are running.
