### ISSUE TITLE
PicoVoice Rhino integration

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#1177]
We want to integrate [PicoVoice Rhino](https://picovoice.ai/docs/rhino/) for intent recognition. 
PicoVoice Rhino handles:
1. Speech to Text
2. Parsing text to 'intent' with some parameters (e.g. intent 'bringItem' with parameters/slot specifying what item to bring and from where to where to bring the item)

So we don't have to run speech recognition and also don't have to use the grammar parser. We still do the process of interpreting this information and acting on it of course.

There is a downside though: the API's we've developed around this process work with a grammar that specifies what sentences are acceptable and what words fill up what parameters. 
That is grammar is still there, on the [PicoVoice console](https://console.picovoice.ai). 

## PicoVoice concepts
In PicoVoice, there are some concepts to know:

- Expression: An Intent can be expressed with different sentences and structures of sentences. Eg. 'Get me item A from the kitchen' or 'Go to the kitchen, get me A and bring it to me' both have the same meaning and intent, but a very different structure. 
    + These expressions are comparable to the grammar definitions the [`grammar_parser`](https://github.com/tue-robotics/grammar_parser) uses.
- Intent: A way to interpret a user's command. eg. `bringItem`, `makeCoffee`.
    + Comparable in function to the Target that the [`grammar_parser`](https://github.com/tue-robotics/grammar_parser) uses.
- Slot: an Intent can fill some slots. eg. what item to bring from where to where, what kind of coffee to make etc. These parametrize the command.
- Context: a collection of various Intents that have some commonality and relation to each other
    + Roughly comparable to a overall grammar definition for the `grammar_parser`.
    + These are referred to via a `context_url`. 

## TODO:
- [ ] Set up Amigo/TechUnited PicoVoice account?
- [ ] Define Contexts+Intents+Slots+Expressions for all our grammars.
    - [ ] yes/no intent
    - [ ] ...
- [ ] Replace our use of grammars within the RoboCup challenges with context_urls and intents.
