### ISSUE TITLE
Kinetic Migration

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#145]
## Waiting for release
- [x] MoveIt! ros-planning/moveit#18
- [ ] rtt_ros_integration https://github.com/orocos/rtt_ros_integration/issues/78
## Misc stuff
- [x] amigo_description xacro dependency
- [x] xacro --inorder [amigo_description/kinetic-devel](https://github.com/tue-robotics/amigo_description/compare/kinetic-devel)
- [ ] let fast_simulator depend on tue_manipulation or move the reference generator to a separate package
- [ ] unfork rosbridge?
- [ ] vocabulary_tree: Please use the FindEigen3.cmake Module provided with Eigen
- [x] sublime?
- [ ] convert all pip install to apt-get install python- (tue-robotics/tue-env#30)
- [x] https://github.com/tue-robotics/ed_sensor_integration has an `old` folder which depends on blackboard.
- [ ] Linking takes ages for some reason ... Stuck on linker now for 5 min :/
## Package build status
- [x] sergio_description
- [x] action_server
- [x] amigo_bringup
- [x] amigo_demo
- [x] amigo_description
- [x] amigo_moveit_config
- [x] base_local_planner
- [x] blackboard
- [x] cb_base_navigation
- [x] challenge_eegpsr
- [x] challenge_final
- [x] challenge_gpsr
- [x] challenge_manipulation
- [x] challenge_navigation
- [x] challenge_open
- [x] challenge_person_recognition
- [x] challenge_restaurant
- [x] challenge_rips
- [x] challenge_robonurse
- [x] challenge_robozoo
- [x] challenge_speech_recognition
- [x] challenge_test
- [x] challenge_wakemeup
- [x] costmap_2d
- [x] dwa_local_planner
- [x] ed
- [x] ed_gui_server
- [x] ed_localization
- [x] ed_navigation
- [x] ed_perception
- [x] ed_rviz_plugins
- [x] ed_sensor_integration
- [x] fast_simulator
- [x] head_ref_ed_client
- [x] multirobot_communication
- [x] nav_core
- [x] nl_robot_console
- [x] robot_skills
- [x] robot_smach_states
- [x] swi_prolog
- [x] tue_manipulation
- [x] tue_robocup
- [x] amigo_head_ref
- [x] amigo_msgs
- [x] ann2
- [x] cb_planner_msgs_srvs
- [x] code_profiler
- [x] dashboard
- [x] dragonfly_speech_recognition
- [x] ed_object_models
- [x] ed_perception_models
- [x] fast_simulator_data
- [x] geolib2
- [x] head_ref
- [x] hmi
- [x] hmi_msgs
- [x] hmi_server
- [x] node_alive
- [x] rgbd
- [x] robocup_knowledge
- [x] robot_launch_files
- [x] rosapi
- [x] rosbridge_library
- [x] rosbridge_server
- [x] rosbridge_suite
- [x] sergio_bringup
- [x] smach
- [x] smach_msgs
- [x] smach_ros
- [x] teleop
- [x] test_tools
- [x] text_to_speech
- [x] tf_server
- [x] tue_config
- [x] tue_costmap_msgs
- [x] tue_filesystem
- [x] tue_manipulation_msgs
- [x] tue_maps
- [x] tue_mobile_ui
- [x] tue_move_base_msgs
- [x] tue_msgs
- [x] tue_recorder
- [x] tue_serialization
- [x] tue_teleop_keyboard
- [x] virtual_cam
- [x] vocabulary_tree
- [x] voxel_grid

**Comment by LoyVanBeek** [comment]
Is " convert all pip install to apt-get install python-" possible for all our packages?

**Comment by Rayman** [comment]
I don't know, we'll have to test this for each package. I found 8 occurences of `pip install`:
https://github.com/tue-robotics/tue-env/search?q="pip+install"

**Comment by Rayman** [comment]
@Timple is this branch ready to merge? [amigo_description/kinetic-devel](https://github.com/tue-robotics/amigo_description/compare/kinetic-devel)

**Comment by Timple** [comment]
I don't know,

I haven't had an opportunity to test it under indigo.

Feel free to make a backup of amigo.urdf, switch to the kinetic-devel
branch, make and compare the differences.

Regards,

Tim

2016-10-25 19:51 GMT+02:00 Ramon Wijnands <notifications@github.com>:

**Comment by Timple** [comment]
Waarom is de package list niet compleet? Ik mis bijvoorbeeld: amigo_hardware

**Comment by Timple** [comment]
Why is rosbridge forked?

**Comment by reinzor** [comment]
sergio description fixed, I think we can go to Kinetic =D

**Comment by reinzor** [comment]
ed rviz plugins also fixed now with qt5

**Comment by Timple** [comment]
Our dear Rayman only evaluated the packages of tue-dev.

However amigo does not run on tue-dev. So some more packages (mostly hardware packages) still need to be evaluated!

**Comment by reinzor** [comment]
Ah ok, I at least can confirm that the simulator is up and running!

**Comment by MatthijsBurgh** [comment]
Saturday, migration of SERGIO?

**Comment by Timple** [comment]
Might be worth looking in to! Depends on the priorities I guess

**Comment by Timple** [comment]
I propose to close this issue since the kinetic migration was succesfully tested. The open items are nice-to-haves. Not requirements.

**Comment by Rayman** [comment]
:+1:

**Comment by Rayman** [comment]
:+1:
