### ISSUE TITLE
[EPIC] Faster grasping

### ISSUE THREAD

**Issue by Timple** [tue-robotics/tue_robocup#147]
- [ ] Quantify current performance
- [ ] Implement [(IKFast)](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/ikfast_tutorial.html)
- [ ] Create single set of acceleration and velocity constraints (MoveIt & LowLevel)
- [ ] Include rotational base joint? tue-robotics/amigo_moveit_config#1
- [ ] Create benchmark script (extreme poses, short movements, long movements, typical movements, random movements, per joint movements, etc)
- [ ] Increase velocity and acceleration of individual joins until the physical limits are reached, reduce parameter by 10%
