### ISSUE TITLE
[EPIC] Robust grasping Demo

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#148]
Demo
- 20 round/square items with a 90% success rate.
- no bumping into the table top
- Significant movement of kinect and arm between of pick-ups

Issues to tackle
- [ ]  Chain of inaccuracies
  - [ ] Inaccuracies in MoveIT
  - [ ] Inaccuracies of homing
  - [ ] Inaccuracies in the arm
  - [ ] Inaccuracies of the localization
  - [ ] Inaccuracies of the object localization
    - [ ] Inaccuracies of the kinect
      - [ ] Inaccuracies in the software
      - [ ] Play in the head
  - [ ] Unable to sample goal state RTT tree Moveit
  - [ ] Sometimes for some reason tries to grasp a non-existing entity (grasp point at position of old entity)
  - [ ] Merge entities
  - [ ] MoveIt segfaults ([amigo/move_group-1] process has died [pid 17134, exit code -11, cmd /opt/ros/indigo/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/home/amigo/.ros/log/a8cd161e-bed1-11e6-ada9-00018080b210/amigo-move_group-1.log].)

Benchmarks
- [ ] Bench-marking of play in the arm with and without homing in between. Bring gripper to same position multiple times, without using MoveIT. Benchmarking without homing shows the play in the arm. Benchmarking with homing shows the performance of homing. This is only visible if play is less than homing inaccuracies.
- [ ] Bench-marking of MoveIT. Let MoveIT compute solution for one goal multiple times. Solution should be the same.
- [ ] Bench-marking of object localization. Place an object on a table. Enter the pipeline multiple times and save all determined positions.
- [ ] Benchmarking of multiple object on same locations to determine influence of object shape on object localization.
- [ ] Bencmarking of head. Unknown.

Solutions
- [ ] In case of play, Create paths which causes the joints to always be in the same side of the play.
- [ ] New, bigger dynamixels.
- [ ] grasping without moving between looking and grasping to eliminate inaccuracies in localization
- [ ] Using gripper marker. According to Rokus, solution is ready for testing.
- [ ] ~~Use sensor in gripper to localize object during grasping.~~
- [ ] Calibration tool to fix inaccuracies caused by parameters in the software.

**Comment by MatthijsBurgh** [comment]
I think the issues
#141 #133 
also should be fixed in this demo. This is essential for robust manipulation.

**Comment by MatthijsBurgh** [comment]
We are working on the solutions, while no benchmarks are performed. This really needs to be done very soon.

**Comment by fibonatic** [comment]
I made a test script for ar markers on the hands of amigo, but there seemed to be quite a big position/rotation error from ar_track_alvar. When testing on amigo, using only rgb images for marker detection, the tf of the markers where placed above and infront of the hands of amigo, instead on its wrists. However the distances between markers seemed correct. It has not been properly tested if including depth information from the kinect (which on initial testing did not seem to improve the detection and positioning) improves this. The branch for this can be found here: https://github.com/tue-robotics/tue_robocup/tree/ar-marker-script/robot_smach_states/scripts

**Comment by LoyVanBeek** [comment]
Yes, if I recall correctly, the tape-measure distance from the Kinect lens to the marekr was 47cm while the distance between the TF's was 50 cm. 
Relative distances (between markers) did match within millimeters. 

Also, the robot model of the wrist looks off: the cylinder on the hand does not line up with the corresponding cylinder on the arm.
