### ISSUE TITLE
[EPIC] Speech recognition

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#149]
- [ ] continous listening (this needs an API change)
  - does this work? Can we just update the speech recognition challenge? What if the robot talks while listening?
- [ ] implement speech server in native windows C# (more speed, bigger grammars and less bugs)
  - investigate the windows C# API of Windows speech --> seems to work, hence ToDos:
  - Determine whether to use static or dynamic loading of the grammar (https://msdn.microsoft.com/en-us/library/hh378481(v=office.14).aspx). Static might be slower because it needs to parse an XML file and generate the C# objects from there. Dynamic does this in one go. Debuggability might be different for the two approaches.  
  - get pipeline working ROS - C# - Windows speech
  - parse 'simple' requests to C# grammar
  - parse 'GPSR' requests to C# grammar
- [ ] sound source localization: see [TDP_golem](http://www.robocup2016.org/media/symposium/Team-Description-Papers/AtHome/RoboCup_2016_AtHome_TDP_golem.pdf)
  - check if the software is available (open source). Don't reinvent the wheel
- [ ] how to serialize the EEGPSR grammer
- [ ] ContinUI
  - [ ] Does this still work?
  - [ ] amigo-hear?
  - [ ] QR code continue for the GPSR

**Comment by MatthijsBurgh** [comment]
I propose to adapt this EPIC to our current plans.
