### ISSUE TITLE
TODO RoboCup Japan

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#255]
## Priority
- [x] tag current master, merge all robocup branches

## ToDo
- [x] right arm does not home
- [ ] fix all challenges in the roboticstestlabs @matthijsburgh
   - [x] RIPS @matthijsburgh
   - [x] SPR @SamAlexandrov 
   - [x] storing groceries @jlunenburg 
   - [x] help me carry @timassman, @fibonatic 
   - [x] GPSR @rokusottervanger 
   - [x] open @MatthijsBurgh  
   - [ ] set the table @SamAlexandrov 
   - [x] restaurant @KevinDang74
   - [x] EEGPSR @rokusottervanger 
   - [x] final @LoyVanBeek (https://github.com/tue-robotics/tue_robocup/pull/296)
- [x] speech recognition improvement (3 challenges we scored low because of this) @Rayman 
   * nuance?
   * different mic?
   *  tue-robotics/dragonfly_speech_recognition#16
   * windows does not automatically log in
   * speech only works when there is an rdp connection
- [x] fixing the action server (GPSR, EEGPSR, nlconsole) @rokusottervanger 
- [x] fix the follow state (should be quick) @LoyVanBeek  
- [x] investigate image recognition false positives (for the groceries challenge) @jlunenburg 
- [x] finalize the KDL refactor (_pose)  @LoyVanBeek 
- [ ] *lots of work* remove `kinect_driver` and implement a `ros_to_rgbd` tool (crashes often) @reinzor 
- [ ] implement the "set the table and tidy-up" challenge @SamAlexandrov 
- [x] Fix help me carry: <strike>tue-robotics/tue_robocup#268</strike>, <strike>https://github.com/tue-robotics/tue_robocup/pull/295 & https://github.com/tue-robotics/tue_robocup/pull/287</strike>
- [x] door in the world model prevents the help me carry challenge to go outside. Please check if this is a problem in other challenges <strike>@MatthijsBurgh please merge: tue-robotics/ed_object_models#5</strike>
- [ ] test grasping at bigger and lower heights
- [ ] visual servoing
- [ ] spr questions related to posture and color
- [x] sound source localization **lots of points**, but low prio
- [x] replace `robot.ed.learn_person` with `robot.head.learn_person` @Rayman
- [x] challenge open: update the starting position @MatthijsBurgh 

## meeting notes
* retraining before the groceries challenge
* image recognition process was too slow and should be improved
* practice image recognition in a more cluttered environment
* world model and knowledge was out of sync
* grammar semantics and the challenge implementations were out of sync

## Hardware
- [x] buy 2 Jetson TX2 dev box
- [ ] <strike>replace Kinect USB-cable</strike>
- [x] fix spindle sensor problem. (at least fix the resetter to check the homing status) @MaxBaeten 

## After Japan
- [x] (Travis) CI
- [ ] dedicated vision node
- [ ] improve body part standardization
- [ ] ed world model in MoveIt

**Comment by Timple** [comment]
Get RGBD out?

**Comment by LoyVanBeek** [comment]
The KDL refactor: It is not yet as pretty as I want it to be, but making breaking changes now will definitely suck. 
The most common issue I've heard is that Entities do not have a FrameStamped. I can add this and leave the current Entity.pose (a geometry_msgs.Pose) and Entity._pose (a kdl.Frame) is place and add Entity.frame_stamped. 

After RoboCup Japan, I'll add deprecation markers to ye olde stuff and convert some more stuff, reducing lines of code.

**Comment by Rayman** [comment]
Are people using `entity._pose`? That would be scary

**Comment by LoyVanBeek** [comment]
:-) It is being used in a couple of places IIRC. This exposed the 'raw' kdl.Frame, while .pose is a property that converts. _pose to a geometry_msgs.msg.Pose to not break everything that depends on it.

**Comment by LoyVanBeek** [comment]
- [ ] Do the Setup up a Table and Tidy Up-task.

**Comment by MaxBaeten** [comment]
Hardware:
- [ ] fix spindle sensor problem. (at least fix the resetter to check the homing status)

**Comment by Rayman** [comment]
- rips: :+1: 
- storing groceries: 55 points (could probably have more points if the kinetic worked)

**Comment by rokusottervanger** [comment]
This issue should be closed IMO. Open checkboxes that are still relevant could be moved to new separate issues. @MatthijsBurgh

**Comment by Rayman** [comment]
For all items there are issues now (or we're not going to to them). Except these two:

- Is set the table working?
- spr questions related to posture and color

**Comment by MatthijsBurgh** [comment]
@SamAlexandrov are questions related to posture and color implemented? Otherwise please create an issue.

**Comment by MatthijsBurgh** [comment]
I think we have a working 'Set the table'. Although I think it could be extended.

**Comment by Rayman** [comment]
Moved to #437
