### ISSUE TITLE
Research object recognition

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/tue_robocup#395]
(issue edited by @LoyVanBeek)
Our performance at RoboCup in japan was **...**. 
The _feeling_ is we do OK when testing but not during actual challenges. 
Before we start making wild guesses, we need to check out current performance and be able to compare performance. 

There are several tracks to work on:
## Other implementations
- [x] Study TDP and create an overview of the [methods used by other teams](https://goo.gl/pFMBWk) :point_right: [Overview](https://github.com/tue-robotics/tue_robocup/files/1387211/object_recognition_research.txt)
- [x] ~(#508) Search the web for state of the art detection algorithms~
- [x] What cloud based object recognition services do exist and how do they perform? Custom labels possible? :point_right: https://github.com/tue-robotics/tue_robocup/issues/395#issuecomment-341902436
- [x] ~(#503) Try the detect net example from NVidia dusty page~
- [x] Investigate if it's feasible to train your own detectnet wich such a small dataset, retraining?
 :point_right: https://github.com/tue-robotics/tue_robocup/issues/395#issuecomment-341906630
- [x] (#505) A difficulty with EDs segmentation from depth is that it doesn't work on translucent objects. How can we improve that? There was a RoboCup team that could detect translucent objects some time ago.

## Improvements on current implementation (i.e. inception_v3 retrained on RoboCup data)
- [x] (#502) Automatically augment training data with noise, occlusions, warps, shears etc. There is a way to do this, but how to activate it? (Also see http://tflearn.org/data_augmentation/) 
- [x] ~Investigate deployment Jetsons using tensorrt.~ Conclusion: runs fine as it is.
- [x] (#509)Measure influence of a margin around the ED-based segmentation. Conclusion: current margin is about the optimum.
- [x] ~(#504)High effort: Refactor ED segmentation to separate ROS service. Allows to plug in different segmenters. RGB(D?) image in --> masked image out~
- [ ] (#521) determine optimal parameters for training: batch size and steps

## (Tools to) measure object recognition performance
- [x] Create easy way to measure accuracy over a test_validation set on certain training data :point_right: https://github.com/tue-robotics/image_recognition/pull/30 

## Measure object recognition performance
- [x] Get lots of images via "amigo, inspect the cabinet/bookcase/dinnertable" and put those in MEGA (#507)
- [x] (#510) Compare the accuracy of a classifier when trained on N classes. Does the accuracy diminish with increasing N classes and how much? Conclusion: Reduce number of classes. So remove classes, which can't be detected. (Maybe also the classes that are always classified wrong/always have a too low probability.)
- [x] (#511)investigate performance of current method (i.e. inception_v3 retrained on RoboCup data) Conclusion: ~60-65% for 25 objects, improvements with limited data is very difficult
- [x] (#509)Annotate those with a large margin around the actual object, so we can test with varying margin down to smaller than the actual object 
- [x] Decide if classification is the problem or that better segmentation will help most (After #509). Conclusion: classification isn't as good as wanted, which would be 80%+

## Different sensors
- [x] (#501) RGBD Sensor selection (also investigate ROS drivers) New camera, but no plans for implementing

@alberth @JosjaG @LoyVanBeek @blumenkindC3

**Comment by reinzor** [comment]
Current implementation: https://github.com/tue-robotics/image_recognition

**Comment by MatthijsBurgh** [comment]
Might be useful, ROS wrapper of darknet: https://github.com/leggedrobotics/darknet_ros

**Comment by reinzor** [comment]
APC vision https://github.com/andyzeng/apc-vision-toolbox#deep-learning-fcn-ros-package

**Comment by reinzor** [comment]
Useful for selecting 3D sensor https://roscon.ros.org/2017/presentations/ROSCon%202017%203D%20Vision%20Technology.pdf

**Comment by LoyVanBeek** [comment]
From @alberth 

aiRobots_NCKU.pdf
=================
For real-time image processing and object recognition system, we
implemented the affine SIFT scheme [5] and the integration of SURF and
BRISK methods [6].  Our paper [6] proposed a real-time object recognition
systems for recognizing known objects and searching unknown objects for home
service robot. The object recognition system is mainly used in recognizing
known objects, which combined Compute Unified Device Architecture (CUDA),
Speeded Up Robust Features (SURF) detector and Binary Robust Invariant
Scalable Keypoints (BRISK) descriptor for improving the computation speed
and decreasing the consumption on memory. On the other side, the visual
perception system is usually used for searching unknown objects, which
calculated the depth differences and found the contours of objects.

[5]. Y.-H. Wang, H.-E. Cheng, C.-J. Lin, R.-W. Deng, H. Lee, and T.-H. S.
Li, “Realization of Affine SIFT Real-time Image Processing for Home
Service Robot,” in Proc. IEEE ICSSE 2013, IEEE Xplore, DOI:
10.1109/ICSSE.2013.6614648, July 2013, Budapest, Hungary.
[6]. H. Lee, C.-Y. Liu, C.-J. Lin, C.-F. Huang, R.-W. Deng, and T.-H. S. Li,
“Implementation of Real-time Object Recognition System for
Home-Service Robot by Integrating SURF and BRISK,” in Proc.
ICSSE, IEEE Xplore, DOI: 10.1109/ICSSE.2014.6887948, Jul. 2014,
Hungary.


Alle@Home.pdf
=============
s a first approach, we have integrated the package
find object 4 which recognizes objects in 2D using SURF descriptors and by means
of the depth information provided by the RGBD sensor, the 3D centroid on the
optical camera frame is computed [7]. Afterwards, the centroid is transformed
into the base coordinate system, whose origin is defined as the centre of the bot-
tom of the robot. We define the object pose by the centroid and a fixed rotation
angle, see Fig. 3.a. Our next approach includes the integration of 3D descriptors
as Fast Point Feature Histograms (FPFH) and deep learning techniques such as
tensorflow

7. Labbé, M. Find-Object. http://introlab.github.io/find-object, 2011. ac-
cessed 2017-03-10.


ASIL-TUT.pdf (HSR)
============
For general ob-
ject recognition, we have developed YOLO[19]-based object recognition system.
For specific object recognition such as particular bottles and cans, we have devel-
oped a method based on image matching[20] using several features, such as Scale
Invariant Feature Transform (SIFT) and Binary Robust Independent Elemen-
tary Features (BRIEF).

19 Yolo: Real-time object detection. https://pjreddie.com/darknet/yolo/.
20 find object 2d - ros wiki. http://wiki.ros.org/find_object_2d.


AUPAIR.PDF
==========
YOLO Ob-ject Detection (You Only Look Once: Unified, Real-Time Object Detection) [1]
(https://pjreddie.com/darknet/yolo/)

Imagenet Object Recognition (https://www.tensorflow.org/tutorials/image recognition)


BahiaRT.pdf (no information)
BIT@home.pdf (no information)
CIT Students @Home.pdf (no information)
CMCopper.pdf (no information)

Duckers.pdf (HSR)
===========
You Only Look Once (YOLO) 4 is used as object recognition algorithm


eR@sers2017.pdf (HSR)
===============
We will enhance our deep learning model for object recognition and motion
generation. The model consists of multiple deep auto-encoders with the time
sequence input of multi-modal information (4).

4. Kuniaki Noda, Hiroaki Arie, Yuki Suga, and Tetsuya Ogata: Multimodal Inte-
gration Learning of Robot Behavior using Deep Neural Networks, Robotics and
Autonomous Systems, Vol. 62, No. 6, pp. 721-736, 2014.


Golem.pdf
=========
Textured objects are recognized using the MOPED
framework proposed by Collet et. al.[2]. SIFT-based object models are obtained
using Structure from Motion. During recognition, SIFT features [6] are obtained
and object hypotheses are made in an iterative manner using Iterative Clustering
Estimation and grouped by Projective Clustering [2].
Golem-III can also recognize textureless objects. This recognition module
first detects horizontal planes and segments objects above them from point
clouds using the Point Cloud Library (PCL)[16]. Then, to recognize the seg-
mented objects, color histograms are computed and compared to a database of
known objects

2. Collet, A., Martinez, M., Srinivasa, S.S.: The MOPED framework: Object Recogni-
tion and Pose Estimation for Manipulation. The International Journal of Robotics
Research 30, 1284–1306 (2011)
16. Rusu, R.B., Cousins, S.: 3D is here: Point Cloud Library (PCL). In: IEEE Inter-
national Conference on Robotics and Automation (ICRA). Shanghai, China (May
9-13 2011)
18. Viola, P., Jones, M.: Rapid object detection using a boosted cascade of simple
features. In: Proceedings of the 2001 IEEE Computer Society Conference on Com-
puter Vision and Pattern Recognition. vol. 1, pp. I–511–I–518 (2001)


HappyMini.pdf
=============
Object recognition: YOLO v2.
Arm control: ROS MoveIt!.


HCRLers.pdf
===========
SLAM is basically
implemented by KINECT device and RTAB ROS Package [10]. In addition, We imple-
ment a 3D people detection algorithm by combining an open-sourced implementation
of a previously trained Convolutional-Neural-Network (CNN) called YOLO [11] with
Euclidean clustering available from the Point Cloud Library (PCL) [12].

The object detection is implemented using Kinect
with the same process of 3D people detection in navigation. We utilize the same pro-
gram structure with one additional interface Find-Object, then, the robot can obtain the
objects’ position using this module.

10. Labbe, M., Michaud, F.: Online global loop closure detection for large-scale multi-session
graph-based slam. IEEE/RSJ International Conference on Intelligent Robots and Systems,
2661-2666 (2014)
11. Redmon, J., Divvala, S., Girshick, R., Farhadi, A.: You only look once: Unified, real-time
object detection. IEEE Conference on Computer Vision and Pattern Recognition, 779-788
(2016)
12. Rusu, R. B., Cousins, S. (2011, May).: 3d is here: Point cloud library (pcl). IEEE Interna-
tional Conference on Robotics and Automation, 1-4 (2011)



Hibikino-Musashi@Home - DSPL.pdf
================================
Our object recognition system has two major parts, which are an object ex-
traction system that obtains images from a camera, and an object recognition
system. The entire processing flow of the object extraction and object recognition
systems are as follows:

1. Obtain a target 3D point cloud as shown in Fig. 4(b), by applying a pass
through-filter to an original 3D point cloud as shown in Fig. 4(a) using a
point cloud library (PCL). The image is obtained using a RGB-D camera on
the HSR.
2. Apply a random sample consensus method, which includes the PCL, to the
target 3D point cloud; this is used to detect the tabletop shown in the blue
part of Fig. 4(c).
3. Clip an object 3D point cloud, which on the table, as shown in Fig. 4(d),
from the target 3D point cloud.
4. Clip an object image from the RGB image using the object 3D point cloud
in order to obtain an object image.
5. Classify the object using a deep neural network (DNN).
6. Calculate the object coordinates using the RGB-D camera coordinate system
and the object 3D point cloud.
7. Change the object coordinates from the RGB-D camera coordinate system
to the robot coordinate system.
8. Control a manipulator so that it moves toward the target coordinates and
grasps the object.

We use Caffe[4], which is a deep learning framework and openCV[5], which is
an image processing library, to construct the object recognition system. For
the deep learning system, we use GoogLeNet[6], which is a 22-layered convolu-
tional neural network that learns using the dataset provided by the Image Net
Large Scale Visual Recognition Challenge 2012[7]. We employ transfer learning
to GoogLeNet, and the final layer is fine-tuned by the dataset that we have cre-
ated for RoboCup@Home. We used a training dataset that has images that are
224 × 224 pixels size, RGB-3Ch, and 8-bit gradation.

4. Caffe. http://caffe.berkeleyvision.org/.
5. Opencv. http://opencv.org/.
6. Christian Szegedy, Wei Liu, Yangqing Jia, Pierre Sermanet, Scott Reed, Dragomir
Anguelov, Dumitru Erhan, Vincent Vanhoucke, and Andrew Rabinovich. Going
deeper with convolutions. In Proceedings of the IEEE Conference on Computer
Vision and Pattern Recognition, pages 1–9, 2015.
7. Imagenet large scale visual recognition challenge 2012. http://image-net.org/
challenges/LSVRC/2012/.


Hibikino-Musashi@Home - OPL.pdf
================================
he process flow of the object-recognition system includes:
1. Obtaining object images of objects using the RGB-D camera and the point
cloud library (PCL)[5], which specialize in two-dimensional (2D) / three-
dimensional (3D) point cloud processing.
2. Recognizing the object in the picture from the previous step using deep
learning[6].

Hibikino-Musashi@Home uses a deep learning framework called Caffe[7]; this
allows us to readily develop a deep neural network. The architecture of the neural
network that our system uses is a 22-layered convolutional neural network called
GoogLeNet[8].

Arm control is performed as the following:
1. Obtain the coordinates of the object using PCL and deep learning.
2. Move the arm into the vicinity of the object.
3. Use ar track alvar to detect the marker on the end effector using the RGB-
D camera; feedback control is then performed to minimize the error with
respect to the target coordinates.

5. Point cloud library. http://pointclouds.org/.
6. Geoffrey E Hinton, Simon Osindero, and Yee-Whye Teh. A fast learning algorithm
for deep belief nets. Neural computation, 18(7):1527–1554, 2006.
7. Caffe. http://caffe.berkeleyvision.org/.
8. Christian Szegedy, Wei Liu, Yangqing Jia, Pierre Sermanet, Scott Reed, Dragomir
Anguelov, Dumitru Erhan, Vincent Vanhoucke, and Andrew Rabinovich. Going
deeper with convolutions. In Proceedings of the IEEE Conference on Computer
Vision and Pattern Recognition, pages 1–9, 2015.


homer@UniKoblenz.pdf
====================
The object recognition algorithm we use is based on
Speeded Up Robust Features (SURF) [1]. First, features are matched between
the trained image and the current camera image based on their euclidean dis-
tance. A threshold on the ratio of the two nearest neighbors is used to filter
unlikely matches. Then, matches are clustered in Hough-space using a four di-
mensional histogram using their position, scale and rotation. This way, sets of
consistent matches are obtained. The result is further optimized by calculating
a homography between the matched images and discarding outliers. Our system
was evaluated in [3] and shown as suitable for fast training and robust object
recognition. A detailed description of this approach is given in [9]
For 3D object recognition we use a continuous Hough-space voting scheme re-
lated to Implicit Shape Models (ISM). In our approach [10], SHOT features [13]
from segmented objects are learned. Contrary to the ISM formulation, we do
not cluster the features. Instead, to generalize from learned shape descriptors,
we match each detected feature with the k nearest learned features in the de-
tection step. Each matched feature casts a vote into a continuous Hough-space.
Maxima for object hypotheses are detected with the Mean Shift Mode Estima-
tion algorithm [2].

1. Herbert Bay, Tinne Tuytelaars, and Luc Van Gool. SURF: Speeded up robust
features. ECCV, pages 404–417, 2006.
2. Yizong Cheng. Mean shift, mode seeking, and clustering. IEEE Transactions on
Pattern Analysis and Machine Intelligence, 17(8):790–799, 1995.
3. Peter Decker, Susanne Thierfelder, Dietrich Paulus, and Marcin Grzegorzek. Dense
Statistic Versus Sparse Feature-Based Approach for 3D Object Recognition. In
10th International Conference on Pattern Recognition and Image Analysis: New
Information Technologies, volume 1, pages 181–184, Moscow, 12 2010. Springer
MAIK Nauka/Interperiodica.

10. Viktor Seib, Norman Link, and Dietrich Paulus. Implicit shape models for 3d shape
classification with a continuous voting space. In Proceedings of International Joint
Conference on Computer Vision, Imaging and Computer Graphics Theory and
Applications, 2015. to appear.

13. Federico Tombari, Samuele Salti, and Luigi Di Stefano. Unique signatures of his-
tograms for local surface description. In Proc. of the European conference on com-
puter vision (ECCV), ECCV’10, pages 356–369, Berlin, Heidelberg, 2010. Springer-
Verlag


JSK@Home.pdf (no information)
KameRiderOPL.pdf (no information)
KameRiderSSPL.pdf (no information)

Machinilog.pdf
==============
Object Detection by our robot is achieved using ‘find_object_2d’ and ‘find_object_3d’
packages of ROS, in which features are extracted and detected by using SIFT and SURF
algorithms whereas image data comes from ASUS Xtion Pro. The recognition is then
achieved by loading the features from the stored images, for detecting images in 3D and
find their coordinates in the 3D space. In future, we plan to use Object Recognition
Kitchen (ORK) [8] for object manipulation.

4. Chitta, Sachin, Ioan Sucan, and Steve Cousins. "Moveit! [ROS topics]." Robotics &
Automation Magazine, IEEE 19.1 (2012): 18-19.
8. Object recognition kitchen http://wg-perception.github.io/object_recognition_core/


MeiBlue.pdf
===========
Uses non-ROS middleware.

In our group, the single camera-based object recognition system has been
developed on OpenRTM-aist[7, 8]. As a pre-processing, the SIFT future detection
and matching is used to detect a target object.

7. Yasushi Mae, Hideyasu Takahashi, Kenichi Ohara, Tomohito Takubo, Tatsuo Arai,
“ Component-based robot system design for grasping tasks ” , Intelligent Service
Robotics, Vol. 4, No. 1, pp. 91-98, 2011.


Minho@Home.pdf (no information)


MRL@home.pdf
============
“ASUS Xtion ProLive” RGB-D camera

Objects in the home environment are placed on horizontal planes, ... we apply
a Plane Model Segmentation method to find dominant plane ... This method uses
RANSAC [2] algorithm ... Point clouds are acquired from RGB-D camera and the
OpenNi framework. ... downsample the points using a Voxelized Grid approach.
... A surface normal needs to be estimated from the surrounding neighborhood of
each point ... K-neighborhood [3]. ... FLANN-based KdTree [4][5] used as the
search method ... .
After segmenting the plane model  ... construct a convex hull polygon for the
set of points supported by the plane ... Euclidean Cluster Extraction algorithm
on extracted indices ... is applied to identify individual objects.

Object recognition: ... the 3D location of the object in the depth
image will be projected into the RGB image plane ... to extract key features of
the object model, an object perception technique vocabulary tree [6] based
Scale Invariant Feature (SIFT) [7] will be applied

[3] D. Bremner, E. Demaine, J. Erickson, J. Iacono, S. Langerman, P. Morin,
and G. Toussaint, “Output-sensitive algorithms for computing nearest-
neighbour decision boundaries,” in Workshop on Algorithms and Data
Structures, Springer, pp. 451–461, isbn: 3540405453.
[4] J. L. Bentley, “Multidimensional binary search trees used for associative
searching,” Communications of the ACM, vol. 18, no. 9, pp. 509–517, 1975,
issn: 0001-0782.
[5] M. Muja and D. G. Lowe, “Fast approximate nearest neighbors with au-
tomatic algorithm configuration,” VISAPP (1), vol. 2, no. 331-340, p. 2,
2009.
[6] D. Nister and H. Stewenius, “Scalable recognition with a vocabulary tree,”
in 2006 IEEE Computer Society Conference on Computer Vision and Pat-
tern Recognition (CVPR’06), vol. 2, IEEE, pp. 2161–2168, isbn: 0769525970.
[7] D. G. Lowe, “Object recognition from local scale-invariant features,” in
Computer vision, 1999. The proceedings of the seventh IEEE international
conference on, vol. 2, Ieee, pp. 1150–1157, isbn: 0769501648.


OIT Challenger.pdf (HSR)
==================
First, object candidate regions are extracted for words specified by human
request. This clustering algorithm is performed by some fast R‐CNN approach [1].

[no details about object recognition, just the global process]

1. Joseph Redmon, Santosh Divvala, Ross Girshick, and Ali Farhadi, "You Only Look Once: Unified, Real‐Time Object Detection," CVPR2016, pp. 779‐788(2016)


OIT-Trial.pdf
=============
RGB-D camera: Xtion PRO LIVE 9 is set on the root position of the arm.

Object recognition by grabbing point cloud data. Robot extracts object regions
using Point Cloud Library[2]. Planes are detected and eliminated by Random
Sample Consensus (RANSAC) algorithm. Euclidean distance based clustering is
applied on the rest of the points.
Recognition by calculating Bhattacharyya distance between H-S histograms of the
extracted clusters and pre-built known objects’ H-S color histograms for
recognition.

2. Radu Bogdan Rusu and Steve Cousins. 3D is here: Point Cloud Library (PCL).
In IEEE International Conference on Robotics and Automation (ICRA), Shanghai,
China, May 9-13 2011.
4. Paul J. Besl and Neil D. McKay. A method for registration of 3-d shapes. IEEE
Trans. Pattern Anal. Mach. Intell., 14(2):239–256, February 1992.


Pumas.pdf
=========
Low or null texture objects recognition using RGB-D cameras. ... we developed
a method that combine three characteristics of the objects: color, size and
shape, after a 3D detection and segmentation in a plane for each object. Color
information is extracted from the HSV space of the object’s RGB pixels and it
is represented by the histogram of the Hue components. The size and shape is
estimated from the object’s point cloud, which are obtained using an oriented
bounding box (OBB) of the points cloud. The shape is characterized using the Hu
Moments [5] of the convex hull calculated from the points projected over the
plane below them.

5. Visual pattern recognition by moment invariants, Ming-Kuei Hu, IRE Transactions
on Information Theory, 8(2):179–187, 1962.


RoboFEI.pdf
===========
Object recognition: SIFT and SURF OpenCV Algorithms.


RT Lions.pdf (no information)

SKUBA.pdf
=========
In order to detect the objects, ... data set to train an object classifier[4]
... . Histogram of Oriented Gradients (HOG) features are extracted ...
and the trained Support Vector Machine (SVM) model ... The detected object location
... is mapped back ... with a 3D point cloud.

4. N. Seo. Tutorial: OpenCV haartraining (Rapid Object Detection With A Cascade
of Boosted Classifiers Based on Haar-like Features). note.sonots.com


SOBITS.pdf
==========
Object recognition consists of two parts. The first one is detecting an object area
by PCL [3]. ... (summary: get point cloud, discard garbage, down-sampling, detect planes (RANSAC), clustering objects on a plane, find area in the RGB image).

We classify the detected object area from PCL into an object by using Caffe[4].

3. Radu Bogdan Rusu and Steve Cousins, “3D is here: Point Cloud Library (PCL)”
   IEEE International Conference on Robotics and Automation, pp.1–4, 2011.
4. Yangqing Jia, Evan Shelhamer, Jeff Donahue, Sergey Karayev, Jonathan Long,
   Ross Girshick, Sergio Guadarrama and Trevor Darrell,“Caffe: Convolutional
   Archi- tecture for Fast Feature Embedding”, Proceedings of the 22nd ACM
   international conference on Multimedia, pp.675–678, 2014.


SPQReL.pdf (no information)

Team EME.pdf
============
For Object detection, we used Object detection Kitchen (ork). In order for the
program to recognize the number of objects, a database has to be built for the
ORK to be trained enough to recognise a certain object.


Team Northeastern.pdf (HSR)
=====================
We have implemented an object detection algorithm called Darknet/YOLO
Object detection framework [13]. YOLO is capable of working in real-time and
doesn’t require high computational resources.

To find object point cloud clusters, firstly, our algorithm finds the table
using RANSAC with plane model [10], then, we extract the point cloud which are
on the table with a threshold. Secondly, Euclidean Clustering is applied to
extract point cloud to find individual clusters of objects. Finally,
Statistical Outlier Removal filter is applied to remove noise.


Tech United DSPL.pdf
====================
Object recognition: Convolution Neural Networks (CNN), Tensorflow ROS


Tech United Eindhoven.pdf
=========================
Object recognition: Convolution Neural Networks (CNN), Tensorflow ROS


Tinker.pdf
==========
In the first phase, a point cloud is built from the Kinect depth camera. Hough
transform and an entropy-based filter is applied to the point cloud to remove
the background. Then a euclidean clustering will give the region of interest.

For object classification, another image processing pipeline is implemented. We
used YOLO9000 [4] for general object type detection. YOLO9000 is a light-weight
while precise nerual networkfor genral object detection and classification.
Then we implemented a bag of words model [5] to pair the object image with
those collected in the library.

4. J. Redmon and A. Farhadi, “Yolo9000: Better, faster, stronger,” 2016.
5. G. Csurka, C. Dance, L. Fan, J. Willamowski, and C. Bray, “Visual
   categorization with bags of keypoints,” in Workshop on statistical learning
   in computer vision, ECCV, vol. 1, no. 1-22. Prague, 2004, pp. 1–2.


ToBI.pdf / ToBI Pepper.pdf
==========================
Object Recongition: CLAFU [16]

16. Roehlig, T.: Indoor room categorization using boosted 2d and 3d features. Master’s
thesis, University of Bielefeld, Citec, Bielefeld, Germany. (2014) Not published.


Tritons.pdf
===========
We have developed a package for object recognition and pose estimation [7]. The
package utilizes CAD models for recognition and estimation. The appearance of
an ob- ject is used for training. Once recognized the pose of the object is
estimated using a set of Lie generators to fit the (CAD) model to observed
edges. ... A more advanced version using RGB-D data has also been developed
[8]. Recognition of natural objects on the fly is fundamental for the
robot-tour scenario [note: their other project].

Object recognition: CNN based recognition

A key challenge is utilization of cloud resources. The repository 3D Warehouse
(former Google 3D warehouse), is a great example of models of objects in do-
mestic environments. We will use the 3D Warehouse resources to perform object
recognition and pose-estimation. We have evaluated the system on a variety of
IKEA furniture [8]. The key challenge here will be scalability to 1000+ objects.
We will use Convolutional Neural Nets (CNN) for the object detection.

7. C. Choi and H. I. Christensen. Robust 3d visual tracking using particle filtering
   on the special Euclidean group: A combined approach of keypoint and edge
   features. Intl. Jour. of Robotics Research, 31(4):498–519, 2012.
8. C. Choi and H.I. Christensen. Rgb-d object pose estimation in unstructured envi-
   ronments. Robotics and Autonomous Systems, 75(1):595–613, January 2016.


Tritons SPL.pdf
===============


UChile Hombreakers.pdf
======================
[Research group on vision / recognition, might be useful to dig deeper what they do?]
[Long discussion on their method "Semantic Segmentation" omitted]

Object recognition: We use a combination of SIFT LR and VFH.


UChilePeppers.pdf (no information)


UNSW@Home.pdf
=============
Asus Xion RGB-D camera.

Simple object detection with the Asus

A relational learning system then builds a description of the object class
based on the relationships between the shape primitive [5]. This method has
been used in the rescue environment to recognise staircases and other terrain
features.

5. R. Farid and C. Sammut. Plane-based object categorisation using relational learn-
ing. Machine Learning, 94(1):3–23, 2013.


UT Austin Villa.pdf (no information)


UTS Unleashed.pdf (HSR)
=================
[Focusses on social robots]

Object recognition and Computer Vision: IBM Watson; Google Vision;
Object recognition kitchen; Amazon Picking Challenge.

UVA@home.pdf (SPL / pepper)
============
The later two approaches make use of datasets recorded with an ASUS Xtion
3D sensor, which make their algorithms direct applicable to the Pepper robot.

WalkingMachine.pdf
==================
An RGB/IR Asus Xtion camera is used in parallel with the Hokuyo (Hokuyo
UTM-30LX on base) to build a 3D map of the environment, but at this point, we
integrated only the 2D map- ping and are using the Xtion camera for object and
people recognition

For objects recognition, we decided to use object recognition kitchen (ORK)
[2] package combine to the Kinect V2, which give us a good quality pointcloud.

WrightEagle.pdf
===============
First the largest horizontal plane is extracted from point cloud using Point
Cloud Library (PCL)[11]. Then point clouds above the plane are clustered into
different pieces as candidates of objects. To improve the detection performance
and reduce false positive rate, clusters with abnormal sizes are filtered
out.Three kinds of features are used in this system: gradients feature in
object contours, HSV color histogram, and SURF feature. First, we use
LINEMOD[8] to detect the contours of object candidates in RGB-D images with
multi-modal templates. Matching based on this feature is unreliable, since
objects with similar shapes have similar contour gradient features. Thus HSV
color histograms are used to reduce false recognitions. After that SURF feature
matching is applied to the rest of the candidates to get the final recognition
results. We also use a joint model[13] to deal with occlusion and small objects
when detect objects. The joint model integrates scene classification, object
and visual phrase detection, as well as scene parsing together. By encoding
them into a Conditional Random Field model, occlusion and small objects could
be solved jointly.

[11] R. B. Rusu and S. Cousins. 3d is here: Point cloud library (pcl). In Pro-
ceedings of the IEEE International Conference on Robotics and Automation,
2011.
[13] I. Ulrich and J. Borenstein. People detection in rgb-d data. In Proceedings
of the 2011 IEEE/RSJ International Conference on Intelligent Robots and
Systems, page 38383843, 2011.

**Comment by LoyVanBeek** [comment]
Popular methods/systems for classification: 
- SIFT, SURF
- YOLO
- GoogleNet
- find_object_2d/3d ROS packages
- Comparing H-S histograms
- ORK
- Google API
- Watson API

**Best team**: Homer@UniKoblenz, using SURF with some additional smart (sounding) tricks.

**Comment by LoyVanBeek** [comment]
Pretrained nets: https://github.com/fchollet/keras/tree/master/keras/applications

**Comment by LoyVanBeek** [comment]
Another suspicion is that the recognition is spoiled by bad segmentation. 
So, how can segmentation be improved? Segmentation from scratch on RGBD-images directly is a waste, because we already do background subtraction in ED with the world model. 

But the edges of the segmentation might be noisy and could thus be improved. We could use this asd a base for so-called 'weak supervision' or as a 'seed' to start the segmentation from. 

For [semantic segmentation](https://github.com/kjw0612/awesome-deep-vision#semantic-segmentation), the competition to look at is based on the [PASCAL VOC2012 dataset](http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=5)

**Comment by alberth** [comment]
I don't know how current ED is perceived, but if you ever want to get rid of the pre-baked world that Amigo needs (as I understood), relying on ED world model subtraction would become a PITA.

**Comment by LoyVanBeek** [comment]
Cloud based object recognition services:
- [Google Vision API](https://cloud.google.com/vision/) (custom labels: :x: )
- [Microsoft Custom Vision (preview)](https://www.customvision.ai/) (custom labels: :white_check_mark: )
- [Microsoft Cognitive toolkit](https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/) (custom labels: :x: )
- [IBM Watson ](https://www.ibm.com/watson/services/visual-recognition/) (custom labels: :white_check_mark: )

**Comment by LoyVanBeek** [comment]
Retraining DetectNet: https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/README.md#model-creation

[DetectNet is derived from GoogLeNet](https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/README.md#detectnet), which is also based on Inception_v3 which we use now. Retraining DetectNet should thus be possible.

**Comment by reinzor** [comment]
What were the conclusions of today\?

-Rein

**Comment by LoyVanBeek** [comment]
@reinzor Not many conclusions (well, that rqt segfaults on my laptop) but mostly following tutorials and general study into this topic. 

People have been tweaking the threshold of putting a classification in the report of the Storing groceries challenge. A metric useful for tuning this could be the Precision-Recall curve:

- http://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html#sphx-glr-auto-examples-model-selection-plot-precision-recall-py 
- http://scikit-learn.org/stable/modules/model_evaluation.html#precision-recall-f-measure-metrics
- http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_curve.html

**Comment by LoyVanBeek** [comment]
Another interesting metric:
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score

**Comment by LoyVanBeek** [comment]
I trained a network on ~/MEGA/data/robotics_testlabs/training_data_Josja/training

I tested the network on our test_data in ```~/MEGA/data/robotics_testlabs/training_data_Josja/test_data```: 
![results](https://user-images.githubusercontent.com/709259/32699933-2c171768-c7be-11e7-8fe8-9b56a9577d55.png). 

and then again with the same data cropped to 90%, to naively get rid of a bit of background:
![results_cropped_90pct](https://user-images.githubusercontent.com/709259/32699956-83541efe-c7be-11e7-9e80-79264fba33bb.png)

**Naively cropping makes classification much worse.** A good segmentation is important.

**Comment by LoyVanBeek** [comment]
TODO:
- [ ] Get lots of images via "amigo, inspect the cabinet/bookcase/dinnertable" and put those in MEGA
- [ ] Annotate those with a large margin around the actual object, so we can test with varying margin down to smaller than the actual object
- [ ] Decide if classification is the problem or that better segmentation will help most

**Comment by LoyVanBeek** [comment]
Trained on 6 classes with 60 images each. 1000 train steps, batch size of 100. 

![results](https://user-images.githubusercontent.com/709259/32805454-c7bded8c-c989-11e7-84be-02d5d3ed7dfe.png)

**Comment by LoyVanBeek** [comment]
More questions:

- [ ] Does using other team's data help or not?
- [ ] How many steps to train with?
- [ ] What batch size to train with?

**Comment by LoyVanBeek** [comment]
More things to try out:
- [ ] Different pre-trained networks (See https://keras.io/applications/ for models and weights)
   - [ ] MobileNet
   - [ ] VGG16
   - [ ] VGG19
   - [ ] Xception
   - [ ] ResNet50

**Comment by LoyVanBeek** [comment]
More things to try out:
- [ ] Different pre-trained networks (See https://keras.io/applications/ for models and weights)
   - [ ] MobileNet
   - [ ] VGG16
   - [ ] VGG19
   - [ ] Xception
   - [ ] ResNet50

**Comment by MatthijsBurgh** [comment]
I trained mobilenet, after I synced the tf_retrain script. Evaluation and classification isn't possible yet. Because the input_tensor "Cast" isn't in the main graph in Mobilenet. I don't know why this is and what the solution is. But using "input" as the input_tensor isn't working, because then the sizes are incorrect.
Probably we need to do JPG decoding in the script?

Network graphs:
### Inception
![inception](https://user-images.githubusercontent.com/18014833/34517770-c357f50c-f07c-11e7-97dd-78c2a8eabbe1.png)
### Mobilenet
![mobilenet](https://user-images.githubusercontent.com/18014833/34517776-c9578f1c-f07c-11e7-8ab4-2d8cdf534a70.png)

**Comment by blumenkindC3** [comment]
I read a Paper about them. I will be back at the 7th, then I can send it
and give u an overview about accuracy and spend.

Am 03.01.2018 12:01 schrieb "Matthijs van der Burgh" <
notifications@github.com>:

**Comment by LoyVanBeek** [comment]
Judging by https://hackernoon.com/creating-insanely-fast-image-classifiers-with-mobilenet-in-tensorflow-f030ce0a2991, I'd  say that indeed the image does need to be resized:
```
python3 tensorflow/examples/label_image/label_image.py \ 
  --graph=/tmp/mobilenet_0.50_192.pb \
  --labels=/tmp/output_labels.txt \
  --image=/home/harvitronix/ml/blogs/road-not-road/test-image.jpg \
  --input_layer=input \
  --output_layer=final_result \
  --input_mean=128 \
  --input_std=128 \
  --input_width=192 \
  --input_height=192
```
