### ISSUE TITLE
[EPIC] RoboCup@Home 2018 Montréal Canada

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/tue_robocup#471]
## Longterm hardware
- [ ] New 3D camera
- [ ] Support from manufacturer
- [ ] ROS-driver
- [x] Matrix Creator
- [ ] Trading new SSL code for free devices
- [ ] Gripper sensor for AMIGO
- [ ] Grasping feedback
- [ ] Grasping loop
- [ ] New laptops
- [ ] ~~(new grippers for AMIGO)~~

## Challenges & Demo (due 10 October)
See https://waffle.io/tue-robotics/tue_robocup to see what's in the current sprint or backlog.

## Object detection & recognition
Members: @reinzor, @LoyVanBeek, @JosjaG, @alberth 
tue-robotics/tue_robocup#395
- [ ] Segmentation!

## Manipulation
Members: @Rayman, @jlunenburg, @MaxBaeten, @hvrooy, @LarsJanssenTUe 
tue-robotics/tue_robocup#402
- [ ] Grasping feedback
- [ ] Grasping loop

## People tracking
Members: @rokusottervanger, @Timple , @SamAlexandrov, @timassman, @KevinDang74 

### SERGIO to Leipzig state
- [ ] Head control
- [ ] Torso calipers calibration
- [ ] General software architecture
- [ ] Matrix Creator & Nvidia Jetson TX2
### SERGIO development by students
- [ ] Torso control
- [ ] Arms
- [ ] Whole body motion control
- [ ] Grippers
- [ ] Navigation for stretched base
