### ISSUE TITLE
Fit tables in Storing Groceries

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#588]
The rules of RoboCup@Home say that a table will be placed anywhere withing 2m of the robot's starting position. We currently don't implement this (it's doubtful if we should, it's not the point of this challenge). 
Which table is not specified, so fitting a model won't be enough

Some [implementation](https://github.com/tue-robotics/tue_robocup/blob/master/challenge_restaurant/src/challenge_restaurant/store_waypoint.py) of this is in the restaurant challenge. That should be ported to Storing Groceries. 
**TODO**: 

- [ ] Use ed.update_kinect(background_padding=...) to find the largest entity left and right of the robot.
- [ ] Set that largest_entity as the table_designator
- [ ] The DefaultGrabDesignator checks for objects on_top_of the table_designator, but unknown/untyped Entities don't have areas/volumes defined. We _could_ add one based on the convex hull of the table entity. 

Instead of using the Kinect, we could try to fit a known table model to the table entity with the _laser_. Not sure how much effort that would be. 

A WIP is on branch feature/dynamic_table

**Comment by MatthijsBurgh** [comment]
This is removed from the challenge.
