### ISSUE TITLE
[EPIC] HERO

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#645]
- [ ] Simulator, tooling, etc @MatthijsBurgh
- [ ] Speech-to-Text @ar13pit, @SamAlexandrov 
    - [ ] Julius: newer model
- [ ]  Robot Skills: @LoyVanBeek, @JosjaG

**Comment by LoyVanBeek** [comment]
Robot_skills entails removing the assumptions about the number of arms and the use of moveit-commander, right? Maybe make separate issues to track each of the subtasks?
