### ISSUE TITLE
[Story] Being able to read SDF in ED/fast_simulator [12/2018]

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#657]
Deadline: End of December 2018
- [x] load sdf in ED #652 
  - [x] add areas to entity instead of reading it from the data everywhere. #681
- [x] load sdf in fast_simulator #659
- [x] tue_config should also accept SDF --> XML #658 
- [x] Model converter to match SDF naming and be converted to XML. [13/11/2018] #651
- [x] SDF Model creator #684
- [x] ~~Map images need to be converted to meshes.~~ #653
- [x] Test the use of `<image>`/`<heightmap>` tag for walls [6/11/2018] #656 
- [x] Gazebo alternative for fast_simulator_data [15/12/2018] #670
