### ISSUE TITLE
[Story] Speech Recognition [01/2019]

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue_robocup#660]
Repository link [speech_recognition](https://github.com/tue-robotics/speech_recognition)
- [x] Complete installation of Kaldi-ASR [#662](https://github.com/tue-robotics/tue_robocup/issues/662)
- [x] Build isolated word recognition system [13/11/2018] [#663](https://github.com/tue-robotics/tue_robocup/issues/663)
- [x] Update documentation [27/11/2018][#664](https://github.com/tue-robotics/tue_robocup/issues/664)
- [x] Integrate with `tue-env`[#665](https://github.com/tue-robotics/tue_robocup/issues/665)
- [x] Make ROS wrapper [12/2018] [#666](https://github.com/tue-robotics/tue_robocup/issues/666)
- [x] Streaming microphone audio to ROS Publisher [#697](https://github.com/tue-robotics/tue_robocup/issues/697)
- [x] Interface the system with HSR (AMIGO too) [01/2019] [#667](https://github.com/tue-robotics/tue_robocup/issues/667)
- [x] Upgrade models to generic English [12/2018] [#668](https://github.com/tue-robotics/tue_robocup/issues/668)
- [ ] Add robocup grammar [01/2019] [#669](https://github.com/tue-robotics/tue_robocup/issues/669)
- [ ] Fix docker implementation #741

**Comment by MatthijsBurgh** [comment]
@ar13pit could you create seperate cards for each subtask? So people can assign themselves to each subtask.

**Comment by ar13pit** [comment]
@MatthijsBurgh it's done.

**Comment by MatthijsBurgh** [comment]
@ar13pit, could you check if some boxes can be ticked? And could you provide a small status update? Is end of January still reachable?

**Comment by ar13pit** [comment]
Closed in favour of #1012
