### ISSUE TITLE
[Story] MoveitCommander [01/2019]

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#673]
- [x] HERO: set-up plain moveit instead of Toyota wrapper #674
- [ ] Fully integrate ed into moveit for collision avoidance [11/2018] #675
- [ ] Integrate MoveitCommander into robot_skills [01/2019] #676

**Comment by MatthijsBurgh** [comment]
@PetervDooren is the deadline: end of January still possible?
