### ISSUE TITLE
add areas to entity instead of reading it from the data everywhere.

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/tue_robocup#681]
- [X] fix new area implementation in ed_view_model in `SDF` branch.
- [x] fix new area implementation in ed_navigation #687
- [x] fix new area implementation in ed_gui_server #688
- [x] fix new area implementation in robot_skills #689
