### ISSUE TITLE
Determine challenges we can do at German Open 2019

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/tue_robocup#727]
# Stage 1
## Housekeeper tasks
- [ ] clean-up
- [ ] gpsr
- [ ] storing-groceries
- [ ] serve-the-breakfast
- [ ] take-out-the-garbage

## Party Host tasks
- [ ] carry-my-luggage
- [ ] farewell
- [ ] find-my-mates
- [ ] receptionist
- [ ] serving-drinks

# Stage 2
## Housekeeper tasks
- [ ] clean-the-table
- [ ] egpsr
- [ ] find-my-disk
- [ ] set-the-table

## Party Host tasks
- [ ] hand-me-that
- [ ] stickler-for-the-rules
- [ ] smoothie-chef
- [ ] where-is-this

**Comment by LoyVanBeek** [comment]
Also see https://github.com/RoboCupAtHome/RuleBook/issues/588

**Comment by ar13pit** [comment]
@MatthijsBurgh @LoyVanBeek Which of these challenges require speech recognition? Because I am not assigned to anything in particular.

**Comment by SamAlexandrov** [comment]
@ar13pit Maybe 'where-is-this' would be most suitable ;)

**Comment by ar13pit** [comment]
@SamAlexandrov but that's stage 2

**Comment by JosjaG** [comment]
@ar13pit gpsr definitely requires speech recognition

**Comment by LoyVanBeek** [comment]
For the Receptionist task, we need to hear names and drinks AFAIK

**Comment by LoyVanBeek** [comment]
Detectoing and classifying people is getting more important: https://github.com/tue-robotics/image_recognition/issues/87 
Challenge `receptionist`, `find_my_mates`, `serving_drinks` all depend on this.
