### ISSUE TITLE
Big RWC 2019 list

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_robocup#871]
Since the board is not actively maintained, I'm using this list to keep track of open issues at RWC 2019

### General
* [x] Fix map: robot should not be able to move round the outside (Lars)
* [x] Speech output not shown on head UI (testing)
* [ ] Speech recognition is crap
* [ ] Odometer dies
* [ ] Too much red and yellow on hero-start and hero-free-mode
* [x] Grasping does not work
* [ ] Filter segmented objects (if height equal to area, probably not a good idea)
* [x] Reduce 'on top of areas' whenever possible (Henk)
* [x] Navigation parameters?
* [ ] Long time issue: camera does not boot
* [x] Force drive: second order trajectory (test)
* [x] Speech bug (test?!)
* [ ] Segmentation bug
* [ ] retrain classification network
* [x] speaker and microphone not working (reboot)

### Restaurant
* [ ] Testing
* [x] Looking people in the eye
* [x] tripple check wave detection (also know the heuristic)
* [x] Instruct barman (something like): "Barman please make sure that the people wave slowly and put their arm up high. Like is shown on my screen"
* [x] picture showing how to wave
* [x] the look angles in find people find person need to be made configurable
( * [ ] ask for continue at bar and at customer)  
( * [ ] laat tray aan geven, voor extra punten)
* [x] over tijd laat het bakje naar beneden
#### Questions
* [ ] Should the robot ask to take an order or just?
* [ ] When using a basket, will you only get a penalty once per order? Or per object? Once per order/object or both for receiving and delivering?
* [ ] Is the tea bag excluded?

#### ToDos
* [x] Cleanup code
* [x] Make sure the challenge does not crash in simulation
* [ ] Grammar too big? (depend on answer to question below)
* [x] Replace say things
* [x] Limit output
* [x] Fix Start of challenge (depend on answer to question below)
* [ ] Factor in 'own' changes
* [x] Add 'general fallback' for 'single item'
* [x] Add fallback for failing speech recognition
* [ ] Fix crash
* [x] Add debugging statements in guiding state
* [x] Add fallback for failing navigation
* [x] Replace speech recognition 'hero' by wait for person in front of robot
* [x] Fallback for lost operator
* [ ] Giving directions/planning a path: what if operator blocks shortest path?
* [x] launch needs to fixed
* [ ] replace stand in front of me by say my name
* [ ] navigate back to the meeting point
* [ ] "my left" instead of your left
* [ ] ask for conformation for location
* [ ] wait for motion done head
* [ ] 5 triggers is to much 
* [ ] "I found you" 
* [ ] check rooms, objects, location
* [ ] come and stand behind me (with sleep)
* [ ] start challenge robust --> ask where to go --> navigate to --> turn 90* head 90* base (180 degree base)
* [ ] feature: describe some more
* [ ] feature: path on screen
* [ ] feature feature extra 300 points unit 
 

#### Questions
* [ ] Where do we need to guide to? Rooms? Furniture objects? Objects at their 'known' locations?
* [ ] How does the challenge start? According to rulebook or as was the case in the German Open?

### Hand me that
* [ ] Narrow down the in front of area. If too wide, inspection might fail
* [ ] Robot (sometimes?) looks at his own hand during inspection
* [ ] Remove previously segmented entities from ED, i.e., reset?

### Clean up (Matthijs)
* [x] 'rooms' are not available
* [x] Robot mentions 'entity' it has seen (pronounces ID)
* [x] Robot does not rise before inspecting (according to Peter not a dramatic issue)
* [ ] Door is detected as entity (put in world model)
* [x] Objects in simulator
* [ ] Grasp the 'most ideal' object
    * [x] Check size of the object
    * [ ] Check position of the object w.r.t. the (edge of the) supporting furniture object

### Receptionist (Loy)
* [ ] Person detection does not work all the time...
    * [x] image of size 0
* [x] Fallback for failing person detection?
* [x] Fix launch files so that ED does not crash due to missing services (mentioned by Rein)
* [x] Challenge crashes (ED detect people not available)
* [ ] Rise robot before human-robot interaction --> does not work well

### RIPS
* [x] Move exit points closer to door
* [x] Check kitchen table position (Lars)

### Take out the garbage (Lars)
* [x] Could not move to the trash_bin
* [x] Cannot pick up trash
* [x] Update map: make sure robot is able to move out of the arena
* [x] Update drop location
* [ ] Testing time
* [ ] Testing fitting
* [ ] Testing general challenge
* [x] Testing force --> does not work
* [x] change map
* [x] update dropping pose
* [x] after picking trash pose dangerously close to wall
* [ ] fitting can give wrong position, to big change get rid of change
* [ ] retract of force down until edge up

### Find My Mates (optional)
* [ ] Integrate new people detector
* [ ] Unique description based on location instead of physical description
* [ ] Describe locations better/differently
* [ ] Skip asking the operator who to describe, simply describe three out of four people
* [ ] On top offs of couch split (local on Lars' pc)

### Serving drinks (Arpit)
* [x] Startup: no 'start challenge robust' (specify point in ed object models and update this in knowledge. Update ed object models once position is known) (Matthijs) --> between shoe_rack and desk
* [x] Check if 'normal' challenge startup works ()
* [x] Rise robot before human interaction
* [x ] Robot needs to hear 'yes' or 'no' but hears something entirely else
* [x] If robot did not 'learn' operator, it doesn't seem able to re-recognize it
    * [x] Learning should work
    * [x] Fallback should be available
* [x] Handover does not work --> construct `OccupiedArmDesignator` and pass this to the Handover class. (Arpit). Alternative: lock the designator. Does the handover from human put the object in the gripper?
* [x] Detect handover: (Josja)
* [x] After handover, *always* return robot to suitable driving position
* [x] Detect waving person and test holding drink fails:
    * [x] Test holding drink separately (Rein)
    * [x] For now: bypass this and go directly to fallback (to speedup)
    * [x] Test waving separately (Rein)
* [ ] Grasping did not work. To fast.
* [ ] Test for drink on other side of bar testing
* [ ] Get rid classification

### Set the table (Rein)
* [ ] Pictures of how to grab objects
* [ ] Complete state testing
* [ ] Skip driving, just turn towards the grabbing position
* [ ] custom place pose dish Henk
* [ ] Drive futher back afte rpalcing (30 cm instead of 10)
* [ ] Place further to the right (esp. for the plate because it's wider)
* [ ] Clear image of how to place bowl and match that with placement. (Can be put in gripper to left or right)
