### ISSUE TITLE
PR robot_smach_states

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/tue_robocup#897]
- [ ] CMakelists.txt
- [x] Makefile
- [ ] navigate_to_place_expl.py
- [ ] console.py (style changes)
- [ ] designator_iterator.py
- [x] .detect_face.py.swp
- [ ] human_interaction/__init__.py (dependent on find_p****_in_room.py and show_image.py)
- [ ] find_people_in_room.py (not for this PR see issue #891)
- [ ] find_person_in_room.py (not for this PR see issue #891)
- [ ] give_directions.py
- [ ] human_interaction.py, merge master into this PR after PR #875.
- [ ] show_image.py
- [ ] manipulation.py
- [ ] control_to_pose.py
- [ ] find.py
- [ ] guidance.py
- [ ] navigate_to_observe.py
- [ ] navigation.py
- [x] rise.py
- [ ] startup.py
- [ ] designators/__init__.py  (dependent on desigators/string_manipulation.py)
- [ ] designators/checks.py
- [ ] designators/core.py
- [ ] designators/ed_designators.py
- [ ] designators/string_manipulation.py
- [ ] designators/utility.py
- [ ] util/dummy_state.py
- [ ] util/startup.py
- [ ] world_model.py
- [ ] test_give_directions.py
- [ ] test_grasping.py
- [ ] test_handover_to_human.py
- [ ] test_navigate_to_observe.py
- [x] test_perception.py (style changes)

**Comment by PetervDooren** [comment]
@LarsJanssenTUe shall I move find_people_in_room.py and find_person_in_room.py to a different PR? Than I can strike them off the list

**Comment by LarsJanssenTUe** [comment]
@PetervDooren, yes I think that that would be a good idea
